import {Link} from 'react-router-dom';import {CheckCircle2,Home as H,Building2,Factory,ShieldCheck} from 'lucide-react';import {site,stats,capabilities,features,brandGroups,clients,sectors} from '../data/site'
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
function Logo({src,name,h}:{src:string,name:string,h:string}){const [ok,setOk]=useState(true);return ok?<img src={src} alt={name} className={h+' w-auto object-contain'} onError={()=>setOk(false)}/>:<span>{name}</span>}
export const Head=({t,s}:{t:string,s?:string})=><div className="text-center mb-10"><h2 className="text-3xl md:text-4xl font-extrabold gradient-text">{t}</h2>{s&&<p className="text-muted mt-2">{s}</p>}</div>
export default function Home(){return(<>
<section className="relative min-h-[calc(100vh-5rem)] flex items-center bg-cover bg-center" style={{backgroundImage:'url(/images/hero.jpg)'}}><div className="absolute inset-0 bg-background/80"/>
<div className="wrap relative text-center slide-up py-16"><img src="/logo.png" alt="TECHSOL emblem" className="h-40 w-40 mx-auto drop-shadow-[0_0_40px_hsl(var(--primary)/.6)]"/>
<span className="inline-flex items-center gap-2 glass !rounded-full px-4 py-1 text-sm mt-6"><ShieldCheck size={16} className="text-primary"/>Your Trusted Security Partner</span>
<h1 className="text-4xl md:text-6xl font-extrabold mt-6 leading-tight">Let us help you create a <span className="gradient-text">secure environment</span> for your loved ones</h1>
<p className="text-primary tracking-[0.25em] text-sm mt-4">{site.tagline}</p><p className="text-muted max-w-2xl mx-auto mt-4">Security, electrical, solar, IoT and AI solutions for homes, businesses and industry across Pakistan and Malaysia.</p>
<div className="flex flex-wrap gap-4 justify-center mt-8"><Link to="/quote" className="btn-primary">Get Your Free Quote</Link><Link to="/solutions" className="btn-ghost">Explore Solutions</Link></div></div></section>
<section className="wrap -mt-8 relative"><div className="glass grid grid-cols-2 md:grid-cols-4 gap-4 p-6 text-center">{stats.map(([v,l])=><div key={l}><div className="text-3xl font-extrabold gradient-text">{v}</div><div className="text-sm text-muted">{l}</div></div>)}</div></section>
<section className="wrap pt-20"><Head t="End-to-End Solutions, Under One Roof"/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{capabilities.map(c=><div key={c} className="glass glass-hover p-4 flex gap-3"><CheckCircle2 className="text-primary shrink-0" size={20}/><span className="text-sm">{c}</span></div>)}</div></section>
<section className="wrap pt-20"><Head t="Key Features"/><div className="grid md:grid-cols-3 gap-6">{features.map(([t,d])=><div key={t} className="glass glass-hover p-6"><h3 className="font-bold text-lg gradient-text">{t}</h3><p className="text-muted text-sm mt-2">{d}</p></div>)}</div></section>
<section className="wrap pt-20"><Head t="Trusted Brands We Deploy" s="Click a logo to visit the manufacturer"/>{Object.entries(brandGroups).map(([g,b])=><div key={g} className="mb-6"><div className="text-xs uppercase tracking-widest text-primary mb-2">{g}</div><div className="flex flex-wrap gap-3">{b.map(([n,u])=><a key={n} href={u} target="_blank" rel="noreferrer" className="glass glass-hover px-5 py-3 font-bold">{n}</a>)}</div></div>)}</section>
<section className="wrap pt-20"><Head t="Satisfied Clients" s="Project Highlights"/><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{clients.map(c=><div key={c.name} className="glass glass-hover overflow-hidden">{c.photo&&<img src={'/images/'+c.photo} alt={c.name} className="h-40 w-full object-cover" onError={e=>(e.currentTarget.style.display='none')}/>}<div className="p-5"><h3 className="font-bold">{c.name}</h3><p className="text-sm text-muted">{c.place} · {c.work}</p></div></div>)}</div></section>
<section className="wrap pt-20"><Head t="Service Categories"/><div className="grid md:grid-cols-3 gap-6">{sectors.map((s,i)=>{const I=icons[i];return <div key={s.key} className="glass glass-hover p-6"><I className="text-primary" size={36}/><h3 className="font-bold text-xl mt-3">{s.title}</h3><p className="text-muted text-sm my-2">{s.desc}</p><ul className="text-sm space-y-1">{s.list.map(l=><li key={l} className="flex gap-2"><CheckCircle2 size={16} className="text-primary"/>{l}</li>)}</ul></div>})}</div></section>
<section className="wrap pt-20 grid md:grid-cols-2 gap-6"><div className="glass p-6"><h3 className="font-bold text-xl gradient-text">Our Commitment</h3><p className="text-muted mt-2">Quality equipment, honest advice and a free 1-year installation warranty on every project.</p></div><div className="glass p-6"><h3 className="font-bold text-xl gradient-text">Affordable Solutions</h3><p className="text-muted mt-2">Transparent PKR pricing and the right-sized system for your budget.</p></div></section>
<section className="wrap pt-20"><div className="glass p-10 text-center"><h2 className="text-3xl font-extrabold gradient-text">Ready to Secure Your Space?</h2><Link to="/quote" className="btn-primary mt-6">Get Your Free Quote</Link></div></section></>)}
