import {useState,ReactNode} from 'react';import {ArrowLeft,ArrowRight,Home,Building2,Factory,Camera,Fingerprint,DoorOpen,Zap,Sun,Cpu,Brain,Construction,FileDown} from 'lucide-react'
import jsPDF from 'jspdf';import autoTable from 'jspdf-autotable';import {site} from '../data/site';import {Cfg,Line,buildBom,disabledFeatures,hddTB,rs} from '../lib/quote'
const SITES=[['Residential',Home],['Commercial',Building2],['Industrial',Factory]] as const
const PROBLEMS=[['Surveillance',Camera],['Attendance & Biometrics',Fingerprint],['Door Access',DoorOpen],['Electrical',Zap],['Solar',Sun],['IoT',Cpu],['Data / AI',Brain]] as const
const DED=['LPR','Hyperlapse','Thermal','PTZ'],FEATS=['Built-In Audio','Built-In Mic','SD Card','High Definition','Dual Light night vision','Full-Color night vision','Dark Areas','Solar Panel','Battery','4G']
const init:Cfg={site:'',count:4,dedicated:[],common:true,kind:'digital',hdds:1,env:'Indoor',days:15,stories:1,rating:'IP66',distance:30,features:[],boxes:'few'}
const Tile=({on,dis,onClick,children}:{on?:boolean,dis?:boolean,onClick:()=>void,children:ReactNode})=><button disabled={dis} onClick={onClick} className={'glass glass-hover p-4 text-left flex items-center gap-3 disabled:opacity-30 disabled:hover:transform-none '+(on?'!border-primary shadow-[0_0_18px_hsl(var(--primary)/.35)]':'')}>{children}</button>
export default function Quote(){
const [step,setStep]=useState(1),[sub,setSub]=useState(0),[c,setC]=useState<Cfg>(init),[soon,setSoon]=useState('')
const [lines,setLines]=useState<Line[]>([]),[ct,setCt]=useState({name:'',phone:'',email:''})
const set=(p:Partial<Cfg>)=>setC({...c,...p});const tog=(k:'dedicated'|'features',v:string)=>set({[k]:c[k].includes(v)?c[k].filter(x=>x!==v):[...c[k],v]} as Partial<Cfg>)
const digital=!c.common||c.kind==='digital'
const subs=['count','dedicated',...(c.dedicated.length?['common']:[]),...(c.common?['kind']:[]),...(digital?['hdd']:[]),'env','days','stories',...(c.env==='Outdoor'?['rating']:[]),'distance','features','boxes']
const cur=subs[sub],dis=disabledFeatures(c),total=lines.reduce((s,l)=>s+l.qty*l.unit,0)
const next=()=>{if(sub<subs.length-1)setSub(sub+1);else{setLines(buildBom(c));setStep(4)}}
const back=()=>{if(step===3&&sub>0)setSub(sub-1);else if(step===4){setStep(3);setSub(subs.length-1)}else if(step===5)setStep(4);else if(step===3||soon){setSoon('');setStep(2)}else setStep(step-1)}
const upd=(i:number,p:Partial<Line>)=>setLines(lines.map((l,j)=>j===i?{...l,...p}:l))
const valid=ct.name&&ct.phone&&/\S+@\S+\.\S+/.test(ct.email)
const book=()=>{window.location.href=`mailto:${site.email}?subject=${encodeURIComponent('Free survey request – '+ct.name)}&body=${encodeURIComponent(`Name: ${ct.name}\nPhone: ${ct.phone}\nEmail: ${ct.email}\nSite: ${c.site}\nCameras: ${c.count}\nEstimated total: ${rs(total)}`)}`;setStep(6)}
const pdf=async()=>{const d=new jsPDF();try{const b=await (await fetch('/logo.png')).blob();const u=await new Promise<string>(r=>{const f=new FileReader();f.onload=()=>r(f.result as string);f.readAsDataURL(b)});d.addImage(u,'PNG',14,10,22,22)}catch{}
 d.setFontSize(20).setFont('helvetica','bold').text(site.name,40,19);d.setFontSize(8).text(site.sub.split('').join(' '),40,24);d.setFont('helvetica','normal').setFontSize(8).text(site.tagline,40,29);d.text(`${site.phone}  |  ${site.email}`,14,38)
 d.setFontSize(10).text(`Quotation for ${ct.name} (${c.site}, ${c.count} camera points)`,14,46)
 autoTable(d,{startY:50,head:[['#','Item','Qty','Unit price (Rs)','Amount (Rs)']],body:lines.map((l,i)=>[i+1,l.name+(l.note?`\n${l.note}`:''),l.qty,l.unit.toLocaleString(),(l.qty*l.unit).toLocaleString()]),foot:[['','','','Total',rs(total)]],styles:{fontSize:8}})
 const y=(d as any).lastAutoTable.finalY+10;d.setFontSize(8).text(d.splitTextToSize('This quotation is tentative and exclusive of taxes. The actual quotation will be provided after site survey. Civil works are not included. Installation charges may be amended after the site visit.',180),14,y);d.save('TECHSOL-Quotation.pdf')}
const nav=(canNext=true)=><div className="flex gap-3 mt-8"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button><button className="btn-primary" disabled={!canNext} onClick={next}>Next<ArrowRight size={16}/></button></div>
const grid=(x:ReactNode)=><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{x}</div>
return(<div className="wrap py-14 max-w-4xl"><h1 className="text-3xl md:text-4xl font-extrabold gradient-text text-center">Free Online Quotation</h1>
<p className="text-center text-muted text-sm mt-1 mb-8">Step {step} of 6{step===3&&` · question ${sub+1}/${subs.length}`}</p>
{step===1&&<><h2 className="font-bold text-xl mb-4">What type of property?</h2>{grid(SITES.map(([n,I])=><Tile key={n} on={c.site===n} onClick={()=>{set({site:n});setStep(2)}}><I className="text-primary" size={28}/><b>{n}</b></Tile>))}</>}
{step===2&&!soon&&<><h2 className="font-bold text-xl mb-4">What do you need?</h2>{grid(PROBLEMS.map(([n,I])=><Tile key={n} onClick={()=>n==='Surveillance'?(setStep(3),setSub(0)):setSoon(n)}><I className="text-primary" size={28}/><b>{n}</b></Tile>))}<div className="mt-6"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button></div></>}
{soon&&<div className="glass p-10 text-center border-warning/50"><Construction className="mx-auto text-warning" size={48}/><h2 className="text-2xl font-extrabold mt-3">Coming Soon</h2><p className="text-muted mt-2">Online quotes for {soon} are on the way. Call {site.phone} or email {site.email} for now.</p><button className="btn-ghost mt-6" onClick={back}><ArrowLeft size={16}/>Back</button></div>}
{step===3&&<div className="glass p-6">
{cur==='count'&&<><h2 className="font-bold text-lg mb-3">Number of camera points</h2><input className="field" inputMode="numeric" value={c.count||''} onChange={e=>set({count:Math.max(0,parseInt(e.target.value.replace(/\D/g,''))||0)})}/>{nav(c.count>0)}</>}
{cur==='dedicated'&&<><h2 className="font-bold text-lg mb-3">Dedicated camera types (optional)</h2>{grid([...DED.map(d=><Tile key={d} on={c.dedicated.includes(d)} onClick={()=>tog('dedicated',d)}><Camera className="text-primary"/>{d}</Tile>),<Tile key="cm" on={c.common} onClick={()=>set({common:!c.common})}><Camera className="text-primary"/>Commonly-used cameras</Tile>])}{nav(c.common||c.dedicated.length>0)}</>}
{cur==='common'&&<><h2 className="font-bold text-lg mb-3">Dedicated cameras are always digital (IP)</h2><p className="text-muted text-sm">Choose how many of each in the quote table later.</p>{nav()}</>}
{cur==='kind'&&<><h2 className="font-bold text-lg mb-3">Common cameras: Analog or Digital (IP)?</h2>{grid(['analog','digital'].map(k=><Tile key={k} on={c.kind===k} onClick={()=>set({kind:k as Cfg['kind']})}>{k==='analog'?'Analog (DVR)':'Digital IP (NVR)'}</Tile>))}{nav()}</>}
{cur==='hdd'&&<><h2 className="font-bold text-lg mb-3">How many hard disks?</h2>{grid([1,2,4,8,16].map(h=><Tile key={h} on={c.hdds===h} onClick={()=>set({hdds:h})}>{h} hard disk{h>1&&'s'}</Tile>))}{nav()}</>}
{cur==='env'&&<><h2 className="font-bold text-lg mb-3">Indoor or outdoor?</h2>{grid(['Indoor','Outdoor'].map(k=><Tile key={k} on={c.env===k} onClick={()=>set({env:k,features:k==='Indoor'?c.features.filter(f=>f!=='Solar Panel'):c.features})}>{k}</Tile>))}{nav()}</>}
{cur==='days'&&<><h2 className="font-bold text-lg mb-3">Days of storage required</h2><input type="number" min={1} className="field" value={c.days||''} onChange={e=>set({days:Math.max(0,+e.target.value)})}/><p className="text-xs text-muted mt-2">About {hddTB(c).toFixed(1)} TB needed in total.</p>{nav(c.days>0)}</>}
{cur==='stories'&&<><h2 className="font-bold text-lg mb-3">Single or multi-story?</h2>{grid(['Single','Multi'].map(k=><Tile key={k} on={(c.stories>1)===(k==='Multi')} onClick={()=>set({stories:k==='Multi'?Math.max(2,c.stories):1})}>{k}-story</Tile>))}{c.stories>1&&<div className="mt-4"><label className="text-sm text-muted">Number of stories</label><input type="number" min={2} className="field" value={c.stories} onChange={e=>set({stories:Math.max(2,+e.target.value||2)})}/><p className="text-xs text-muted mt-2">{Math.ceil(c.count/c.stories)} cameras per floor; PoE switches split per floor.</p></div>}{nav()}</>}
{cur==='rating'&&<><h2 className="font-bold text-lg mb-3">Outdoor protection rating</h2>{grid(['IP66','IP67','IK10'].map(k=><Tile key={k} on={c.rating===k} onClick={()=>set({rating:k})}>{k}</Tile>))}{nav()}</>}
{cur==='distance'&&<><h2 className="font-bold text-lg mb-3">Capture distance</h2>{grid([20,30,50,100,150,300,500].map(k=><Tile key={k} on={c.distance===k} onClick={()=>set({distance:k})}>{k} m</Tile>))}{nav()}</>}
{cur==='features'&&<><h2 className="font-bold text-lg mb-3">Features</h2>{grid(FEATS.map(f=><Tile key={f} dis={dis.includes(f)} on={c.features.includes(f)} onClick={()=>tog('features',f)}>{f}</Tile>))}{nav()}</>}
{cur==='boxes'&&<><h2 className="font-bold text-lg mb-3">Camera junction boxes</h2>{grid([['all','All cameras'],['few','A few'],['none','None']].map(([k,l])=><Tile key={k} on={c.boxes===k} onClick={()=>set({boxes:k as Cfg['boxes']})}>{l}</Tile>))}<div className="flex gap-3 mt-8"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button><button className="btn-primary" onClick={next}>Build my quote</button></div></>}</div>}
{step>=4&&step<6&&<div className="glass p-4 md:p-6"><h2 className="font-bold text-xl mb-4">{step===4?'Bill of materials':'Edit your quote'}</h2>
<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-muted text-left"><tr><th className="p-2">Item</th><th className="p-2">Qty</th><th className="p-2">Unit (Rs)</th><th className="p-2 text-right">Amount</th></tr></thead><tbody>{lines.map((l,i)=><tr key={l.id} className="border-t border-border/30"><td className="p-2">{l.name}{l.note&&<div className="text-xs text-muted">{l.note}</div>}</td>
<td className="p-2">{step===5?<input type="number" min={0} className="field !w-20" value={l.qty} onChange={e=>upd(i,{qty:Math.max(0,+e.target.value)})}/>:l.qty}</td><td className="p-2">{step===5?<input type="number" min={0} className="field !w-28" value={l.unit} onChange={e=>upd(i,{unit:Math.max(0,+e.target.value)})}/>:l.unit.toLocaleString()}</td><td className="p-2 text-right">{rs(l.qty*l.unit)}</td></tr>)}</tbody></table></div>
<div className="text-right text-2xl font-extrabold gradient-text mt-4">{rs(total)}</div><p className="text-xs text-muted text-right">Tentative, exclusive of taxes.</p>
{step===4&&<div className="flex gap-3 mt-6"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button><button className="btn-primary" onClick={()=>setStep(5)}>Edit &amp; continue<ArrowRight size={16}/></button></div>}
{step===5&&<><h3 className="font-bold mt-8 mb-3">Book your free survey</h3><div className="grid md:grid-cols-3 gap-3">{(['name','phone','email'] as const).map(k=><input key={k} className="field" placeholder={k[0].toUpperCase()+k.slice(1)} value={ct[k]} onChange={e=>setCt({...ct,[k]:e.target.value})}/>)}</div><div className="flex gap-3 mt-6"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button><button className="btn-primary" disabled={!valid} onClick={book}>Book survey</button></div></>}</div>}
{step===6&&<div className="glass p-10 text-center"><h2 className="text-2xl font-extrabold gradient-text">Thank you, {ct.name}!</h2><p className="text-muted my-3">Your email app opened with your request. Download your quotation below.</p><div className="flex gap-3 justify-center"><button className="btn-ghost" onClick={back}><ArrowLeft size={16}/>Back</button><button className="btn-primary" onClick={pdf}><FileDown size={16}/>Download PDF</button></div></div>}
</div>)}
